PortalNoticias/Models/Noticia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortalNoticias.Models
{
    public class Noticia
    {
        public int Id { get; set; }

        public string Titulo { get; set; }

        public string Autor { get; set; }

        public DateTime Data { get; set; }

        public string Conteudo { get; set; }
    }
}

PortalNoticias/Models/RepositorioNoticias.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortalNoticias.Models
{
    public static class RepositorioNoticias
    {
        private static List<Noticia> _noticias;

        public static List<Noticia> Noticias
        {
            get {
                    if (_noticias == null)
                        CriarNoticias();
                    return _noticias;
            }
        }

        private static void CriarNoticias()
        {
            _noticias = new List<Noticia>();

            _noticias.Add(new Noticia() {
                Id = 1,
                Titulo = "Palmeiras acerta venda de Keno para time do Egito por R$ 37 milhões",
                Autor = "Blog do Palmeiras",
                Data = DateTime.Today.Date,
                Conteudo = "Palmeiras acertou nesta segunda-feira a venda do atacante Keno. Depois de negociações nas últimas semanas, " +
                "o clube teve as exigências atendidas e definiu a transferência do atleta para o Al Ahram Pyramids FC, do Egito, " +
                "por US$ 10 milhões (cerca de R$ 37,8 milhões). O Verdão vai ficar com 100% do valor da transferência.O anúncio " +
                "foi feito pelo clube como o mais caro da história da liga egípcia"
            });
            _noticias.Add(new Noticia()
            {
                Id = 2,
                Titulo = "Torcida do Palmeiras comemora gol de Mina na Copa do Mundo; zagueiro manda abraço.",
                Autor = "Globo.com",
                Data = DateTime.Today,
                Conteudo = "Zagueiro Yerry Mina deixou o Palmeiras em janeiro deste ano. Mas, mesmo distante e vestindo a camisa " +
                "do Barcelona, o colombiano voltou a ser assunto entre os torcedores do Verdão neste domingo, quando ele marcou de " +
                "cabeça e abriu caminho para a vitória da Colômbia por 3 a 0 contra a Polônia, pela segunda rodada do Grupo H da Copa " +
                "do Mundo."
            });
            _noticias.Add(new Noticia()
            {
                Id = 3,
                Titulo = "Time sub-17 do Palmeiras aplica goleada de 17 a 0 no Paulistão da categoria",
                Autor = "Blog do Palmeiras",
                Data = DateTime.Today.Date.AddDays(1),
                Conteudo = "Time sub-17 do Palmeiras fez história no Campeonato Paulista ao, neste domingo, golear o São José " +
                "por 17 a 0, em partida válida pela 12ª rodada do torneio estadual da categoria. O jogo foi disputado no estádio " +
                "Novelli Junior, em Itu. Na quinta rodada da competição, os palmeirenses já haviam goleado a equipe de São José " +
                "dos Campos por 16 a 1.Os atacantes Fabricio, autor de sete gols, e Gabriel Silva, que marcou cinco vezes, foram " +
                "os destaques da vitória alviverde. Tatavitto, Victor Pires, Rondinely, Gabriel Veron e Geilson fecharam o placar " +
                "histórico."
            });
        }
    }
}

PortalNoticias/Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PortalNoticias.Models;

namespace PortalNoticias.Controllers
{
    public class NoticiasController : Controller
    {
        // GET: Noticias
        public ActionResult Index()
        {
            return View(RepositorioNoticias.Noticias);
        }

        public ActionResult Detalhes(int id)
        {
            var noticia = RepositorioNoticias.Noticias.FirstOrDefault(n => n.Id == id);
            return View(noticia);
        }

        public ActionResult Buscar(string texto)
        {
            var noticias = RepositorioNoticias.Noticias.Where(n => n.Titulo.ToUpper().Contains(texto.ToUpper()) || n.Conteudo.ToUpper().Contains(texto));
            return View(noticias);
        }
    }
}

PortalNoticias/Views/Noticias/Buscar.cshtml
@model IEnumerable<PortalNoticias.Models.Noticia>

@{
    ViewBag.Title = "Buscar";
}

@foreach (var @item in Model)
{

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title"><strong>@item.Titulo</strong></div>
        </div>
        <div class="panel panel-body">
            <p>@item.Conteudo.Substring(0, 100) ...</p>
        </div>
        <div class="panel panel-footer">
            <div class="btn btn-default">
                @Html.ActionLink("Ler mais", "Detalhes", new { id = item.Id })
            </div>
        </div>
    </div>
}

@{
    if (Model.Count() == 0)
    {
        <p>Nenhuma notícia encontrada.</p>
        @Html.ActionLink("Voltar para home page", "Index", "Noticias")
    }
}

PortalNoticias/Views/Noticias/Detalhes.cshtml
@model PortalNoticias.Models.Noticia

@{
    ViewBag.Title = "Detalhes da Notícia";
}

<h2><strong>@Model.Titulo</strong></h2>

<p>Publicado por <strong>@Model.Autor</strong> em <strong>@Model.Data.ToString("dd/MM/yyyy")</strong></p>

<p>@Model.Conteudo</p>


 @Html.ActionLink("Voltar a home page", "Index", "Noticias")

PortalNoticias/Views/Noticias/Index.cshtml
@model IEnumerable<PortalNoticias.Models.Noticia>

@{
    ViewBag.Title = "Notícias";
}


@foreach (var item in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="panel-title"><strong>@item.Titulo</strong></p>
        </div>
        <div class="panel-body">
            <p>@item.Conteudo.Substring(0, 100) ...</p>
        </div>
        <div class="btn-default">

        </div>
        <div class="panel-footer">
            @Html.ActionLink("Ler mais", "Detalhes", new { id = item.Id }, new { @class = "btn btn-default" })
        </div>
    </div>
}

PortalNoticias/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Portal de Notícias</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container">

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Home", "Index", "Noticias", null, new { @class = "navbar-brand" })
                </div>

            </div>
        </div>

        <div class="jumbotron text-center">
            <h1>Portal de Notícias</h1>
        </div>

        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <p class="panel-title">Buscar Notícia</p>
                    </div>
                    <div class="panel-body">
                        @using(Html.BeginForm("Buscar", "Noticias", FormMethod.Get))
                        {
                            <input type="text" class="form-control" name="texto" placeholder="Buscar por..." />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>